apiVersion: v1
kind: Service
metadata:
    name: "intellipixdemo-3d27"
    labels:
        app: "intellipixdemo-3d27"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "intellipixdemo-3d27"