on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: intellipix20220914105637.azurecr.io
        username: ${{ secrets.acr_intellipix20220914105637_username }}
        password: ${{ secrets.acr_intellipix20220914105637_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t intellipix20220914105637.azurecr.io/intellipixdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push intellipix20220914105637.azurecr.io/intellipixdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_intellipixdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep intellipixdemoa00c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace intellipixdemoa00c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: intellipixdemoa00c
        container-registry-url: intellipix20220914105637.azurecr.io
        container-registry-username: ${{ secrets.acr_intellipix20220914105637_username }}
        container-registry-password: ${{ secrets.acr_intellipix20220914105637_password }}
        secret-name: intellipixdedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: intellipixdemoa00c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          intellipix20220914105637.azurecr.io/intellipixdemo:${{ github.sha }}
        imagepullsecrets: |
          intellipixdedockerauth
